# Generated by Django 4.1.1 on 2022-10-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_cartproduct_cart_alter_cartproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
